### ISSUE TITLE
I'm a lazy reader...pls help me

### ISSUE THREAD

**Issue by andresyncier** [AdrianFel/Script-basics#1]
As a lazy reader, I would like to have a short version of a text, for that, based in a original txt file, I would like to have on my terminal output which contains every second line only.
Example:

```
My name is Andre
I am 38 years old
I don't have any hobbies
but I like beer, games and music
```

the result file should look like

```

I am 38 years old

but I like beer, games and music
```

**Comment by AdrianFel** [comment]
I'm done
