### ISSUE TITLE
Word counting

### ISSUE THREAD

**Issue by andresyncier** [AdrianFel/Script-basics#3]
As a business people, I would like to have as a terminal output some metrics based on a text file:
 - How many lines are in the file
 - How many chars are in total ( including blank spaces )
 - How many chars are in each line  ( including blank spaces )
 
Example:
```
My test file first line
My test file second line
```
Output:
```
 2 lines
 47 characters in total
 line 1 contains 23 chars
 line 2 contains 24 chars
```

**Comment by AdrianFel** [comment]
I'm done

**Comment by AdrianFel** [comment]
yes.
